name: Download raw minutes

on:
  repository_dispatch:
    types: download_minutes
  #schedule:
  #  - cron:  '*/5 * * * *'
  # 0 18 * * TUE

jobs:
  download-minutes:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup custom environment variables
      run: git config --global push.default simple && git config --global user.email "w3c.ccg@gmail.com" && git config --global user.name "W3C CCG"
    - name: Pull raw meeting log file
      id: pull_raw_file
      env: 
        DATE: ${{ github.event.client_payload.date }}
        GROUP_NAME: ${{ github.event.client_payload.groupName }}
        GROUP_ALIAS: ${{ github.event.client_payload.groupAlias }}
      run: |
        export OUTPUT_DIR=${DATE}
        if [ ! -z "$GROUP_ALIAS" ];then
          export OUTPUT_DIR=${OUTPUT_DIR}-${GROUP_ALIAS}
        fi
        bash ./download-minutes.sh
        echo "##[set-output name=date;]${DATE}"
        echo "##[set-output name=groupName;]${GROUP_NAME}"
        echo "##[set-output name=outputDir;]${OUTPUT_DIR}"
      shell: bash
    - uses: stefanzweifel/git-auto-commit-action@v2.5.0
      with:
        commit_message: Add raw log for telecon [ci skip]
        branch: gh-pages
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send email
      uses: dawidd6/action-send-mail@v1.3.0
   
      with:
        server_address: smtp.gmail.com
        server_port: 465
        username: w3c.ccg
        password: ${{ secrets.email_password }}
        subject: ${{ format('[ACTION - clean up raw minutes] W3C {0} Call - {1} 12pm ET', steps.pull_raw_file.outputs.groupName, steps.pull_raw_file.outputs.date) }}
        body: ${{ format('Go to scribe-tool (https://w3c-ccg.github.io/meetings/scribe-tool/), paste in the contents of https://raw.githubusercontent.com/w3c-ccg/meetings/gh-pages/{0}/irc-raw.log, clean it up, save results in irc.log (same folder) and commit.', steps.pull_raw_file.outputs.outputDir) }}
        to: kimdhamilton@gmail.com
        from: W3C CCG Chairs
